# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_rpc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import grpc_service.rpc.basic_pb2 as basic__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10server_rpc.proto\x12\x05proto\x1a\x0b\x62\x61sic.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\tDataArray\x12\x0e\n\x06values\x18\x01 \x03(\t\"\xbe\x01\n\x1b\x63lient_column_dict_response\x12T\n\x12\x63lient_column_dict\x18\x01 \x03(\x0b\x32\x38.proto.client_column_dict_response.ClientColumnDictEntry\x1aI\n\x15\x43lientColumnDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.proto.DataArray:\x02\x38\x01\";\n\x13\x62\x61tch_query_request\x12$\n\nquery_list\x18\x01 \x03(\x0b\x32\x10.proto.dataframe\">\n\x14\x62\x61tch_query_response\x12&\n\x0cquery_result\x18\x01 \x03(\x0b\x32\x10.proto.dataframe\"7\n\x14single_query_request\x12\x1f\n\x05query\x18\x01 \x01(\x0b\x32\x10.proto.dataframe\"?\n\x15single_query_response\x12&\n\x0cquery_result\x18\x01 \x01(\x0b\x32\x10.proto.dataframe\"\x82\x01\n\x16server_config_response\x12\x39\n\x06\x63onfig\x18\x01 \x03(\x0b\x32).proto.server_config_response.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xc4\x02\n\rServerService\x12I\n\x0csingle_query\x12\x1b.proto.single_query_request\x1a\x1c.proto.single_query_response\x12\x46\n\x0b\x62\x61tch_query\x12\x1a.proto.batch_query_request\x1a\x1b.proto.batch_query_response\x12T\n\x16get_client_column_dict\x12\x16.google.protobuf.Empty\x1a\".proto.client_column_dict_response\x12J\n\x11get_server_config\x12\x16.google.protobuf.Empty\x1a\x1d.proto.server_config_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENT_COLUMN_DICT_RESPONSE_CLIENTCOLUMNDICTENTRY']._options = None
  _globals['_CLIENT_COLUMN_DICT_RESPONSE_CLIENTCOLUMNDICTENTRY']._serialized_options = b'8\001'
  _globals['_SERVER_CONFIG_RESPONSE_CONFIGENTRY']._options = None
  _globals['_SERVER_CONFIG_RESPONSE_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_DATAARRAY']._serialized_start=69
  _globals['_DATAARRAY']._serialized_end=96
  _globals['_CLIENT_COLUMN_DICT_RESPONSE']._serialized_start=99
  _globals['_CLIENT_COLUMN_DICT_RESPONSE']._serialized_end=289
  _globals['_CLIENT_COLUMN_DICT_RESPONSE_CLIENTCOLUMNDICTENTRY']._serialized_start=216
  _globals['_CLIENT_COLUMN_DICT_RESPONSE_CLIENTCOLUMNDICTENTRY']._serialized_end=289
  _globals['_BATCH_QUERY_REQUEST']._serialized_start=291
  _globals['_BATCH_QUERY_REQUEST']._serialized_end=350
  _globals['_BATCH_QUERY_RESPONSE']._serialized_start=352
  _globals['_BATCH_QUERY_RESPONSE']._serialized_end=414
  _globals['_SINGLE_QUERY_REQUEST']._serialized_start=416
  _globals['_SINGLE_QUERY_REQUEST']._serialized_end=471
  _globals['_SINGLE_QUERY_RESPONSE']._serialized_start=473
  _globals['_SINGLE_QUERY_RESPONSE']._serialized_end=536
  _globals['_SERVER_CONFIG_RESPONSE']._serialized_start=539
  _globals['_SERVER_CONFIG_RESPONSE']._serialized_end=669
  _globals['_SERVER_CONFIG_RESPONSE_CONFIGENTRY']._serialized_start=624
  _globals['_SERVER_CONFIG_RESPONSE_CONFIGENTRY']._serialized_end=669
  _globals['_SERVERSERVICE']._serialized_start=672
  _globals['_SERVERSERVICE']._serialized_end=996
# @@protoc_insertion_point(module_scope)
