# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import grpc
import grpc_service.rpc.server_rpc_pb2 as server__rpc__pb2


class ServerServiceStub(object):
    """定义server节点的rpc服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.single_query = channel.unary_unary(
                '/proto.ServerService/single_query',
                request_serializer=server__rpc__pb2.single_query_request.SerializeToString,
                response_deserializer=server__rpc__pb2.single_query_response.FromString,
                )
        self.batch_query = channel.unary_unary(
                '/proto.ServerService/batch_query',
                request_serializer=server__rpc__pb2.batch_query_request.SerializeToString,
                response_deserializer=server__rpc__pb2.batch_query_response.FromString,
                )
        self.get_client_column_dict = channel.unary_unary(
                '/proto.ServerService/get_client_column_dict',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=server__rpc__pb2.client_column_dict_response.FromString,
                )
        self.get_server_config = channel.unary_unary(
                '/proto.ServerService/get_server_config',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=server__rpc__pb2.server_config_response.FromString,
                )


class ServerServiceServicer(object):
    """定义server节点的rpc服务
    """

    def single_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batch_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_client_column_dict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'single_query': grpc.unary_unary_rpc_method_handler(
                    servicer.single_query,
                    request_deserializer=server__rpc__pb2.single_query_request.FromString,
                    response_serializer=server__rpc__pb2.single_query_response.SerializeToString,
            ),
            'batch_query': grpc.unary_unary_rpc_method_handler(
                    servicer.batch_query,
                    request_deserializer=server__rpc__pb2.batch_query_request.FromString,
                    response_serializer=server__rpc__pb2.batch_query_response.SerializeToString,
            ),
            'get_client_column_dict': grpc.unary_unary_rpc_method_handler(
                    servicer.get_client_column_dict,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=server__rpc__pb2.client_column_dict_response.SerializeToString,
            ),
            'get_server_config': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_config,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=server__rpc__pb2.server_config_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """定义server节点的rpc服务
    """

    @staticmethod
    def single_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.ServerService/single_query',
            server__rpc__pb2.single_query_request.SerializeToString,
            server__rpc__pb2.single_query_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def batch_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.ServerService/batch_query',
            server__rpc__pb2.batch_query_request.SerializeToString,
            server__rpc__pb2.batch_query_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_client_column_dict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.ServerService/get_client_column_dict',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            server__rpc__pb2.client_column_dict_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_server_config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.ServerService/get_server_config',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            server__rpc__pb2.server_config_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
